### ISSUE TITLE
code issue

### ISSUE THREAD

**Issue by pengyiwu** [RameezI/TUeLaneTracker#7]
hello,where can i see the underlying algorithm for the lane detection and tracking?
thanks so much.

**Comment by RameezI** [comment]
The algorithm is contained in the following DAG (Directed Cyclic Graph)  files:
[BufferingDAG_generic.cpp](https://github.com/RameezI/TUeLaneTracker/blob/master/TUeLDT/BufferingDAG_generic.cpp)
[TrackingLaneDAG_generic.cpp](https://github.com/RameezI/TUeLaneTracker/blob/master/TUeLDT/TrackingLaneDAG_generic.cpp)
